travis:
  secure:
    BINSTAR_TOKEN: k5y5OYLG7dNPJdFoEi0qgArhX2eZXMa7hPcV8nCnBf3FcRGfBO1VZvlw3u+wIkk2Jv2p6QeKOcTncxQ6wC2L1tm4AkdjpyM7q665RN2mbTpPUEOo0c/KQioN3tKU+gz/3EEV+gUQeN2MNStTa+dv25D3Q8mWvhYbejQFj40OULjHdG+l8D4hRPO60QMT5EcjYEL8IJ1ZcJR9LhB4yrolwB8IsS+BKEfIEjVr7nD0YPlw/CJ3i9IJKzIpq/4gxTYqZbzFACDZTgrAdEdTt8Tri1klTihZoPZayCXaJDM2l60ALERuGmUORcfQpHxZMMkHgRWiz9aqiWg6nrP95n2jeT9ZxV6QFYJOwMSTazHUrtgzjN3m1fiBXOoySEKrx+xbhUvJt4CQ7aOBWwcFwLQ6rll/5xDlc1ugeJPih/3M02L4paGWoo9iajQpN+2nUi3MbreSPv2iXPFmcXSjrXJ4+txLu5BUQVOwDwHPcym8nTLQffyEjXd7NJe10L0vHi7Olg2jdSef2Gw32rVTE+82zuxpR6/jTTcrfbeAnqdJ85bZAA+jAGeaHPnIq+hRk51VwsOOlAAr2z/62YdE+Qagqrmch+srPVrtCPAFLCXt/8/XVU0jyRnA2Sf9Pfwnuik9n/XU3akGAcaFvbs0Y5CTc0E/Ov6PduTvlTrctCyQncc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
